github:
  token: "![hW2k2Z4Ber7hNE6iRB2YXm6C9T437s1iuY8mhpesqhi7xVrwTWyErlMRE+/okcKy1gMSXv59o08+BciBGECHc03kqIM9odHc47XAY7CrqHqGxZGem51718LFsoRwQQjpojswRZ9mJawSEzDEnI8erw==]"
  webhookSecret: "![zbuntO0nUXsuOaJDs8O9WMR3TWsjmyZSknbQJgIJmbe2fMDlkYy/HyERRTE8WwCTXZHpC66P80JpNIHo7ncDV8/IwsB+fiyTb6rB6xBTLTD0tH2Q31lzdGHvFjdyoHQN]"
anypoint:
  clientId: "![pKapTVdaHPkk5Qk9wXlMPX8sYbVGC0uvgzA/kSAUAKmm/gWtp8L7Ks7y0KlvWj/speCxECoiSMhUZ0hIK2YM5A==]"
  clientSecret: "![FofzoI+VO/wVY4TcnRjRjPGY/WiN/FhywpKSo/vY/tuG3Bnol04bTBBLmUqYw5acIfy0jUVfGR1sVF+43JrBVA==]"
slack:
  webhookUrl: "![GrCBr22cWZK3Roe3fIVXgfk+n6iMYWhfKceE6BbwyDy6rglkjg2PTTotI6QT394/efG3SLxQXzglLHM9xJIKKhDQj6a3SnxZPXtnAekd9m/PcbOujVGjZSUO/0zZv9tJzCNLi5IkxPAeO+97HOrf4A==]"
jira:
  email: "![i4a9ZcCunqthV5D9XAhud1fuvYdOn7fAkNpLpxdHxHk5ByzQtSvUrgqsqk7O/ZNx]"
  apiToken: "![xTxMFWDISoXJjmoBJBYfrAWIeJNs68BbJ9GULo2PkkLy/xs81jmuA/4DOIMCVMLzfqF7D96gaKHRMVooXt4qBknSTU2i0WKoQ2Z+eHMX9sSK1mDgXUwfeNTFQHS19AIcdckigV6TqcBl/sZMOmFk94CToyljhom2Sca6pmSX8Bca0av0Q0/0Lo6MWTa7+Nw8P65ZVYhgSkW3ciL1DIFDvwXXcyrYjr9qjm4hmHKBAXIWnFStEumPPt8uX9FpFMGv5I9AbYMwrt4Y2GZMSzQkqgEP94WAZNdtrNQnp1C3xXY=]"
